//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032_MVC_News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleDetail
    {
        public int ArticleId { get; set; }
        public string ArticleTitle { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string ArticleContent { get; set; }
        public string AuthorId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
